// =================================================================
// SUPABASE CONFIG — paste your two values below to enable global leaderboard
// =================================================================
//
// IMPORTANT: Supabase recently changed their UI. Here's how to find the keys
// in the CURRENT (2025+) Supabase dashboard:
//
// STEP 1 — Get your Project URL:
//    Project Settings (gear icon, bottom of left sidebar) → "API" or "Data API"
//    OR: Click the green "Connect" button at the top of any page
//    Look for "Project URL" — it looks like https://xxxxxxxxxxxx.supabase.co
//    Paste it between the quotes in SUPABASE_URL below.
//
// STEP 2 — Get your anon (public) key:
//    Project Settings → API Keys
//    The default tab now shows "Publishable key" + "Secret keys" (NEW FORMAT).
//    Click the "Legacy anon, service_role API keys" TAB instead.
//    Copy the LONG STRING next to "anon public" — it starts with "eyJ..."
//    Paste it between the quotes in SUPABASE_ANON_KEY below.
//
//    (The new sb_publishable_* keys also work, but the legacy anon key is
//     what this code is tested with. Use the legacy tab for now.)
//
// STEP 3 — NEVER paste your "Secret key" or "service_role" key here.
//    Those bypass security. They belong on a server, not in browser code.
//    You only need the publishable/anon key for this game.
//
// STEP 4 — Run the SQL block at the bottom of this file ONCE in your
//    Supabase SQL editor (Project → SQL Editor → New query → paste → Run).
//    This creates the "scores" table and security policies.
//
// =================================================================

export const SUPABASE_URL = "https://zofbqhloihbcoqjgtsyi.supabase.co";          // e.g. "https://zofbqhloihbcoqjgtsyi.supabase.co"
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZmJxaGxvaWhiY29xamd0c3lpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODA3NjEzNywiZXhwIjoyMDkzNjUyMTM3fQ.HVeNqOXoMvMwQDyX6a8yizs5ZDyi8h6xvjiZV-3kGSA";     // long JWT starting with eyJ...

// =================================================================
// ONE-TIME SQL SETUP — run this in Supabase SQL Editor exactly once.
// (Project → SQL Editor in the left sidebar → New query → paste → Run)
// Copy everything between the /* and */ markers below.
// =================================================================
/*

-- Create the leaderboard table
create table if not exists scores (
  id           bigint generated by default as identity primary key,
  name         text not null,
  score        integer not null,
  stage        integer not null default 1,
  country      text,
  created_at   timestamp with time zone default now()
);

-- Enable Row Level Security (required by Supabase)
alter table scores enable row level security;

-- Allow anyone to READ scores (needed to display the leaderboard)
drop policy if exists "anyone can read" on scores;
create policy "anyone can read" on scores
  for select using (true);

-- Allow anyone to INSERT scores, with sanity checks against cheaters
drop policy if exists "anyone can insert" on scores;
create policy "anyone can insert" on scores
  for insert with check (
    char_length(name) between 1 and 14
    and score >= 0
    and score <= 10000000
    and stage between 1 and 99
  );

-- Index for fast leaderboard queries
create index if not exists scores_score_idx on scores (score desc);

*/
