// =================================================================
// SUPABASE CONFIG
// =================================================================
// To enable the global leaderboard, paste your two values here:
//
// 1. Go to https://supabase.com  →  log in  →  pick your project
// 2. Open: Project Settings (gear icon) → API
// 3. Copy "Project URL" → paste in SUPABASE_URL below
// 4. Copy "Project API keys" → "anon" "public" → paste in SUPABASE_ANON_KEY below
// 5. Save the file. Game will auto-detect and switch from local to global.
//
// If you leave these empty, the game runs perfectly on a LOCAL leaderboard.
// =================================================================

export const SUPABASE_URL = "https://zofbqhloihbcoqjgtsyi.supabase.co";          // e.g. "https://abcdefg.supabase.co"
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZmJxaGxvaWhiY29xamd0c3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwNzYxMzcsImV4cCI6MjA5MzY1MjEzN30.qddh_qnvFaYGp57OkmH-0mgXxmd82Q0bGZDNUDrnzI8";     // long string starting with eyJ...

// Once you paste your keys, also run this SQL in your Supabase project (SQL Editor):
/*
  create table if not exists scores (
    id           bigint generated by default as identity primary key,
    name         text not null,
    score        integer not null,
    stage        integer not null default 1,
    country      text,
    created_at   timestamp with time zone default now()
  );

  alter table scores enable row level security;

  create policy "anyone can read" on scores
    for select using (true);

  create policy "anyone can insert" on scores
    for insert with check (
      char_length(name) between 1 and 14
      and score >= 0
      and score <= 10000000
      and stage between 1 and 99
    );

  create index if not exists scores_score_idx on scores (score desc);
*/
